# Generated by Django 3.1.2 on 2020-10-29 15:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0001_add_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\project\\saejulproject-main\\saejulproject\\media'), upload_to=''),
        ),
    ]
